---
mountpoint: "/mnt/firebird_backup"
restore_db: false
create_alias: true
setup_backup: true

firebird_db_path: "/opt/bockermann"
firebird_db_name: "SCHLAUCH.FDB"
firebird_db_alias: "schlauch"

firebird_database_admin_user: sysdba
firebird_database_admin_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34393330393932346335366438366166326236663633306332333234653865636263633264616437
          3165366632333134636266306336393066663837373632310a306163643563666361303938636539
          35393833646632396536633435376137643865303762646566666162396263376430656636636233
          6265393835386238370a663563626536646230353435333734653634396564306464643731393764
          3363
firebird_database_user: FLORIX
firebird_database_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37373165306138643266626562346139373936666165316437393239373039333939643233316531
          3831333539383337336261616139383732613733316438660a373432366662363636633138333237
          34636265323263373163366333643361333264373734646162616264373230333230346330356234
          6562643565376464630a336336613433633231316561663961613264386331663834336634303034
          3138

# NFS
permissions: "644"
nfs_src: stark.feuerwehr.weingarten.local:/Firebird_Backup_Bockermann
options: vers=4,rw,rsize=8192,wsize=8192,timeo=14,intr,user

# NTP
ntp_timezone: Europe/Berlin
