---
# NTP
ntp_timezone: Europe/Berlin

# NFS
nfs_permissions: "644"
nfs_mountpoint: "/mnt/backup"
nfs_src: stark.feuerwehr.weingarten.local:/Backup_PSQL_Prod
nfs_options: vers=4,rw,rsize=8192,wsize=8192,timeo=14,intr

# PSQL
setup_backup: true

psql_db_semaphore_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30643139373263636436323861613165306331636339396366383837343932633534646335323830
          3136383437343066656435376435663332346362666633370a303832616136616263333531396234
          64666639376336333935646337313839303238383237353735396235316533353265613130303333
          6661363839316536380a333534363266616265393138313464363934396562643531636563616234
          64366462366533613230313465663732653831666238363333366462336238303934623630613831
          37353235353731653138343564383331323665663936336437613634613233396562306533313961
          626461633138666538343737353335633030

psql_db_traccar_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65653331376332333363343965646563383163333235623637303865633066383832663736346638
          3737336531623236633665356263316235613162633237380a373565616336616163333833623363
          65643538373065386266613234613130636636363436616262663966373038663230643533336263
          3039313135376463380a356165666335633164353833623763303466623062616637366663326231
          30396230356361613632343066313761393432306662363133356134653136616664663632646236
          33393838616131663463366164346131636132343237363264303462373334626265306263643930
          656464663431313939363133383331386535