---
# NTP
ntp_timezone: Europe/Berlin

# NFS
nfs_permissions: "644"
nfs_mountpoint: "/mnt/backup"
nfs_src: stark.feuerwehr.weingarten.local:/Backup_PSQL_Test
nfs_options: vers=4,rw,rsize=8192,wsize=8192,timeo=14,intr

# PSQL
setup_backup: true

psql_db_semaphore_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30643139373263636436323861613165306331636339396366383837343932633534646335323830
          3136383437343066656435376435663332346362666633370a303832616136616263333531396234
          64666639376336333935646337313839303238383237353735396235316533353265613130303333
          6661363839316536380a333534363266616265393138313464363934396562643531636563616234
          64366462366533613230313465663732653831666238363333366462336238303934623630613831
          37353235353731653138343564383331323665663936336437613634613233396562306533313961
          626461633138666538343737353335633030

psql_db_traccar_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30316334396335663231653065353831346534663032346532366363313234643932393834623365
          3038336330626565343534386431313064393666333038300a616131323566633533613033343662
          66336162623161323835663837613436303461346633626239346234313737383265663061316463
          3739653064363066380a636338653564633537666637396532393738383732346638336266333935
          61636139383537636135663865326661663536316536353637666666323461386665663263626632
          39363665323662303462316163326636663862326437303838663631343962323034363462353662
          636465343066363963393261363233313765